# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: valentus
# "service" is the name of this project. This will also be added to your AWS resource names.
service: solar-forecast-bot

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    LAT: ${env:LAT}
    LON: ${env:LON}

functions:
  morning:
    handler: handler.morning
    events:
      - schedule:
          rate: cron(0 4 * * ? *)
  evening:
    handler: handler.evening
    events:
      - schedule:
          rate: cron(0 19 * * ? *)

package:
  patterns:
    - "**/*.ts"
